<?php
$scriptList = array('jquery-3.1.0.min.js', 'carousel.js');
include('php/header.php');
?>

<div id="main">
    <p>
        Welcome to Classic Cinema, your online store for classic film.
    </p>
    <div id="carousel">
        <!-- Content generated by JavaScript in carousel.js -->
    </div>
</div>

<?php
    include ("php/footer.php");
?>
